{{/*
Connection strings.

Each store is either installed by this chart or supplied by the operator, and
the app must not have to know which. These helpers resolve that in one place:
enabled means "use the in-cluster service", disabled means "use the value from
.Values.connections".

The previous chart version left pgDSN and amqpURL as empty strings marked
"required", which rendered a perfectly valid manifest whose pods then
crash-looped on start. Anything that must be set is now either derived or
checked in _validate below.
*/}}

{{- define "netinv.pgSecretName" -}}netinv-data{{- end -}}

{{/*
Password handling for the chart-installed stores.

Generated once and then read back out of the Secret on every subsequent render,
because `randAlphaNum` is re-evaluated on each `helm upgrade`: without the
read-back, an upgrade would hand the application a brand new password for a
database whose password had not changed, and every service would fail to
connect immediately after a routine upgrade.

`lookup` returns nothing when there is no cluster to query — `helm template`,
`--dry-run`, and GitOps renderers all hit this path. There the password is
freshly generated each render, which is why values.yaml recommends setting it
explicitly if you render manifests offline.
*/}}
{{- define "netinv.dataPassword" -}}
{{- $ctx := .ctx -}}
{{- $key := .key -}}
{{- $explicit := .explicit -}}
{{- if $explicit -}}
{{- $explicit -}}
{{- else -}}
{{- $existing := (lookup "v1" "Secret" $ctx.Release.Namespace (include "netinv.pgSecretName" $ctx)) -}}
{{- if and $existing (index $existing.data $key) -}}
{{- index $existing.data $key | b64dec -}}
{{- else -}}
{{- randAlphaNum 24 -}}
{{- end -}}
{{- end -}}
{{- end -}}

{{- define "netinv.pgPassword" -}}
{{- include "netinv.dataPassword" (dict "ctx" . "key" "PG_PASSWORD" "explicit" .Values.data.postgres.password) -}}
{{- end -}}

{{- define "netinv.amqpPassword" -}}
{{- include "netinv.dataPassword" (dict "ctx" . "key" "AMQP_PASSWORD" "explicit" .Values.data.rabbitmq.password) -}}
{{- end -}}

{{- define "netinv.pgDSN" -}}
{{- if .Values.data.postgres.enabled -}}
postgres://{{ .Values.data.postgres.username }}:{{ include "netinv.pgPassword" . }}@netinv-postgres:5432/{{ .Values.data.postgres.database }}?sslmode=disable
{{- else -}}
{{- .Values.connections.pgDSN -}}
{{- end -}}
{{- end -}}

{{- define "netinv.amqpURL" -}}
{{- if .Values.data.rabbitmq.enabled -}}
amqp://{{ .Values.data.rabbitmq.username }}:{{ include "netinv.amqpPassword" . }}@netinv-rabbitmq:5672/
{{- else -}}
{{- .Values.connections.amqpURL -}}
{{- end -}}
{{- end -}}

{{- define "netinv.redisAddr" -}}
{{- if .Values.data.redis.enabled -}}netinv-redis:6379{{- else -}}{{- .Values.connections.redisAddr -}}{{- end -}}
{{- end -}}

{{- define "netinv.vmURL" -}}
{{- if .Values.data.victoriametrics.enabled -}}http://netinv-victoriametrics:8428{{- else -}}{{- .Values.connections.vmURL -}}{{- end -}}
{{- end -}}

{{/*
The URL that goes into alert notifications. An alert whose "view in NetInv"
link goes nowhere is worse than an alert with no link, so this falls back to
the ingress host rather than rendering an empty string.
*/}}
{{- define "netinv.uiURL" -}}
{{- if .Values.uiURL -}}
{{- .Values.uiURL -}}
{{- else if .Values.ingress.enabled -}}
{{- if .Values.ingress.tlsSecret -}}https://{{ .Values.ingress.host }}{{- else -}}http://{{ .Values.ingress.host }}{{- end -}}
{{- end -}}
{{- end -}}

{{- define "netinv.labels" -}}
app.kubernetes.io/name: netinv
app.kubernetes.io/instance: {{ .Release.Name }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end -}}

{{/*
Fail the render, not the runtime.

Every one of these produces a healthy-looking install whose pods crash-loop or
whose data is unrecoverable, and all of them are cheap to catch here.
*/}}
{{- define "netinv.validate" -}}
{{- if not .Values.secrets.existingSecret -}}
{{- fail "secrets.existingSecret is required: NETINV_MASTER_KEY encrypts every stored device credential and is never generated by this chart (see values.yaml)" -}}
{{- end -}}
{{- if and (not .Values.data.postgres.enabled) (not .Values.connections.pgDSN) -}}
{{- fail "data.postgres.enabled is false, so connections.pgDSN must be set" -}}
{{- end -}}
{{- if and (not .Values.data.rabbitmq.enabled) (not .Values.connections.amqpURL) -}}
{{- fail "data.rabbitmq.enabled is false, so connections.amqpURL must be set" -}}
{{- end -}}
{{- if and (not .Values.data.redis.enabled) (not .Values.connections.redisAddr) -}}
{{- fail "data.redis.enabled is false, so connections.redisAddr must be set" -}}
{{- end -}}
{{- if and (not .Values.data.victoriametrics.enabled) (not .Values.connections.vmURL) -}}
{{- fail "data.victoriametrics.enabled is false, so connections.vmURL must be set" -}}
{{- end -}}
{{- if and .Values.networkPolicy.enabled (not .Values.networkPolicy.deviceCIDRs) -}}
{{- fail "networkPolicy.enabled with an empty networkPolicy.deviceCIDRs would deny the poller every device and stop collection; list the device subnets" -}}
{{- end -}}
{{- end -}}
